// <auto-generated />
namespace GigHubMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddNewConventionsOnGigsAndGenres : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddNewConventionsOnGigsAndGenres));
        
        string IMigrationMetadata.Id
        {
            get { return "202206141627106_AddNewConventionsOnGigsAndGenres"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
